# netlify.toml
[build]
  # run everything from within frontend/
  base    = "frontend"
  # npm ci is faster and more repeatable in CI
  command = "npm ci && npm run build"
  # after cd frontend, Vite builds into dist/
  publish = "dist"

# single‑page‑app fallback so React Router works
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
