# Generated by Django 5.2.4 on 2025-07-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
