# Generated by Django 5.2.4 on 2025-07-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0002_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="due_date",
        ),
    ]
