# Generated by Django 5.2.4 on 2025-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0003_remove_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodlog",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
