# Generated by Django 5.2.4 on 2025-07-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0004_alter_moodlog_recorded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodlog",
            name="recorded_at",
        ),
    ]
