# Generated by Django 5.2.4 on 2025-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0005_remove_moodlog_recorded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodlog",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
