# Generated by Django 5.2.4 on 2025-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0006_moodlog_recorded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
