# Generated by Django 5.2.4 on 2025-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0007_task_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodlog",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "Happy"),
                    ("calm", "Calm / Content"),
                    ("neutral", "Neutral"),
                    ("irritable", "Irritable / Frustrated"),
                    ("sad", "Sad / Low"),
                    ("anxious", "Anxious / Overwhelmed"),
                    ("restless", "Restless / Jittery"),
                    ("burnt_out", "Burnt Out"),
                    ("stressed", "Stressed / Panicky"),
                    ("focused", "Focused / On Track"),
                ],
                max_length=20,
            ),
        ),
    ]
