# Generated by Django 5.2.4 on 2025-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhd_backend", "0009_alter_moodlog_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodlog",
            name="mood",
            field=models.CharField(
                choices=[
                    ("Happy", "Happy"),
                    ("Calm", "Calm / Content"),
                    ("Neutral", "Neutral"),
                    ("Irritable", "Irritable / Frustrated"),
                    ("Sad", "Sad / Low"),
                    ("Anxious", "Anxious / Overwhelmed"),
                    ("Restless", "Restless / Jittery"),
                    ("BurntOut", "Burnt Out"),
                    ("Stressed", "Stressed / Panicky"),
                    ("Focused", "Focused / On Track"),
                    ("Angry", "Angry"),
                ],
                max_length=20,
            ),
        ),
    ]
